# Simple script to execute SQL commands with Azure authentication
param(
    [string]$AccessToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InlFVXdtWFdMMTA3Q2MtN1FaMldTYmVPYjNzUSIsImtpZCI6InlFVXdtWFdMMTA3Q2MtN1FaMldTYmVPYjNzUSJ9.eyJhdWQiOiJodHRwczovL2RhdGFiYXNlLndpbmRvd3MubmV0LyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzY4N2Y1MWMzLTBjNWQtNDkwNS04NGY4LTk3YzY4M2E1YjlkMS8iLCJpYXQiOjE3NjIzNDA5MjUsIm5iZiI6MTc2MjM0MDkyNSwiZXhwIjoxNzYyMzQ0ODY0LCJhY3IiOiIxIiwiYWlvIjoiQVhRQWkvOGFBQUFBaUxFU2paUlJPVXBOZjhrS3FiZ2pBVlNBNGFaakxjWThHc0VyRlNObGNSMUpWa0o5MENlbFBFeWZxSVorQVlNaUs3RmJtdHBxelRuSlFacHRoQzk1bW1MaEhVTTI2bmYrQkxUWCtjYkxIOENIM2lJTWk2U3lOL2t2VFhDamV3OXhLclIxSFFvMkFwVXdWNmlLZDdVSUVBPT0iLCJhbXIiOlsicHdkIiwicnNhIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZGV2aWNlaWQiOiI3YTE2YjQyYy0wZGYwLTRjNjUtYWFhZS05ZDJhYjA3NDNkOGYiLCJmYW1pbHlfbmFtZSI6IlNhbSIsImdpdmVuX25hbWUiOiJTaGliaW4iLCJncm91cHMiOlsiOTk5MWQ3MGEtMWU1ZS00YTkwLThlZjEtZTRhOTM4MDc3Mjg3IiwiYTJlMDk5MTItN2MyNS00ZmRjLWJkZjMtMDFiM2ZmOTI0MWM1IiwiODBkOGI0MWItOTFiZS00MTY4LWJhMTQtMTViMjgwMDk0N2FhIiwiODNjMDYxMzYtMDZiOS00NmYxLTk5MTEtN2M2NmY2M2Q3MjM2IiwiYjNlYTYwNGItMjM2My00Mzg1LWEyODUtYWRlZGJhN2I3NWVhIiwiOTZmY2NmNTUtZTc1MC00NmNlLWFiMDItZGM5ZDMxNTJmYjA3IiwiNDVjMjkxNWQtNGM4ZS00ZjViLWIzMTYtNGFiYjM0OGM5YjFjIiwiMWY1OGFhNjItYjgxMy00MjhiLTg4ZGEtN2I1ODdiNWYzMGUwIiwiNzUyYzAxNmItODJmMS00Zjg2LTllZDQtNWI0YjhiNDM5OWQ5IiwiODJjYWQ2NzAtMmI5YS00NDM0LTg1ODQtNjkxZDkxNjUxYTY4IiwiMGY2YmVkNzEtMzgyYi00NDQzLWEwZmYtODNkZmZkODdhNTk0IiwiNDgyNjg2NzUtNzc5Ni00ZTIxLWE5MDYtZWExMjU4ZGFiY2M5IiwiODkyODE0NzgtNjE3Yi00MGQwLWJhODUtY2E2ZTM2MTYzMmI4IiwiNTMzOWJlN2MtZTBlYy00MTNhLTk0ZmEtNzljN2RlMWU3ODQzIiwiOGM2OGM1ODAtZTNlZC00M2U4LTgxZGUtNDQ2MTdjNDg0NjVmIiwiNjhjNDZlODktMzU5Yi00ZmJlLWI4Y2EtODQ4YzU3ZjdlOTVhIiwiYzIxYjc1OWQtZjEyOC00YThmLWJiYzAtYzA2NjllZWNhZTY2IiwiYjdkM2QyYjgtNGI4NC00NmNmLWFmMTUtMmU1NmQ0OTAwMmM0IiwiZDFiYTY1YzAtMTc0YS00MGQ0LWE0YTctYTBhZDRjNjZlZDI1IiwiMmFkNGU4ZDUtOWJiNy00ZWU4LTk1MTItMTQwZjI4YTI2MzBkIiwiZGYxMzVjZDctN2QxNi00ZGM3LWI5YWEtYjUzNTdiODk2M2ExIiwiNjU5ZTdmZGEtYzM2Ny00NjkyLWJiYWEtNDAyYzI3N2Q4OTNlIiwiY2FiZmJhZTEtNzNlNy00MGI5LThmNzAtYTllZDhhMWYyZTZlIiwiNzJiNzdmZTItMzM2Yy00ZTkyLTkwY2ItNjBlNDU4ODJlOWI4IiwiMzI1OTNiZWUtYTllMi00N2Y3LWI2OTAtOGI3YzE1ZTlhZmMzIiwiZTExZTJlZmItMzk0OC00ZjBkLWEzMzgtY2RmOGZmZWRhOTAzIiwiNzFlMTIyZmUtMjkyMC00N2U1LThhNmQtNDU4NmQ5MzZmMjBlIl0sImlkdHlwIjoidXNlciIsImlwYWRkciI6IjguMjkuMjMxLjUyIiwibmFtZSI6IlNoaWJpbiBTYW0iLCJvaWQiOiJlMjQzMThkNC02MmE1LTQ5Y2QtYjcxYi02NjhmNGI2Mjg2N2UiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNDM2Mzc0MDY5LTQ4NDc2Mzg2OS0xNzA4NTM3NzY4LTc2MTI5IiwicHVpZCI6IjEwMDMyMDAzOERDMTM2NTciLCJyaCI6IjEuQVJzQXcxRl9hRjBNQlVtRS1KZkdnNlc1MGRNSEtRSWJEX2RJdXR3YnBxdXJiV2JZQUxrYkFBLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZCI6IjAwODlkMTU5LWIyY2QtMzhiZS0yMGZhLTU2NWQ1NDcwYzZhYyIsInN1YiI6InUtNFpkWGVZTVF4cFg5aHdIMjFEcTBLbnJGVHF1ZG85V1RTcWVzeUo3eW8iLCJ0aWQiOiI2ODdmNTFjMy0wYzVkLTQ5MDUtODRmOC05N2M2ODNhNWI5ZDEiLCJ1bmlxdWVfbmFtZSI6IlNoaWJpbi5TYW1AbmV1ZGVzaWMuY29tIiwidXBuIjoiU2hpYmluLlNhbUBuZXVkZXNpYy5jb20iLCJ1dGkiOiJiOE9OcHlPdk5VYVBaNEd3bWhtUUFBIiwidmVyIjoiMS4wIiwieG1zX2FjdF9mY3QiOiIzIDUiLCJ4bXNfZnRkIjoiTF81Smg0Mmw5bFF4YmhieDY3cF9uVGZvR0p2dXh2UHpPSlRleXRRN2RTVUJkWE56YjNWMGFDMWtjMjF6IiwieG1zX2lkcmVsIjoiMSAyNiIsInhtc19zdWJfZmN0IjoiMyAxNCJ9.DApRrg3lussp_U1xfRmbZLg4kubZjKbsYSq5m7g5zfv5jyEfNXFVgtL8do_AhwRGz_d_81O8SwrncaHPacruKzB7-JOZc3-zKl2iPv2hNGN6BCZExLYZzp0F19y9V21Hm0Xzgbytavaw-X5xyNgp6qhU9OQ0o1FLkjRDpcRzJKTz5akqG8L0y8RJ4P349V1JIHuiglpYQqLjNDSkKuHI6ZDO6A-qNlPPvw5rWl0YNKDLnOh_AKQ6tFrWDi4Rt2Ag6Aq4Eab-eMxfk18cU5y77PCkHIpPQ75cpA4zy1sa3-Bzgnxjh-YhYIe8emhykJdmBQsE3TeigG_lN0eVy2xZLA"
)

$serverName = "aistrainingserver.database.windows.net"
$databaseName = "empdb"
$logicAppName = "upsert-employee"

# SQL command to grant access
$sqlCommand = @"
CREATE USER [$logicAppName] FROM EXTERNAL PROVIDER;
ALTER ROLE db_datareader ADD MEMBER [$logicAppName];
ALTER ROLE db_datawriter ADD MEMBER [$logicAppName];
GRANT SELECT, INSERT, UPDATE ON dbo.Employee TO [$logicAppName];
SELECT 'Access granted successfully' AS Result;
"@

try {
    Write-Host "Granting SQL Database Access..." -ForegroundColor Yellow
    
    # Use .NET SqlConnection with access token
    Add-Type -AssemblyName "System.Data"
    $connectionString = "Server=$serverName;Database=$databaseName;Encrypt=True;TrustServerCertificate=False;"
    
    $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
    $connection.AccessToken = $AccessToken
    $connection.Open()
    
    $command = $connection.CreateCommand()
    $command.CommandText = $sqlCommand
    $result = $command.ExecuteScalar()
    
    Write-Host "SUCCESS: $result" -ForegroundColor Green
    
    $connection.Close()
}
catch {
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Trying alternative approach..." -ForegroundColor Yellow
    
    # Alternative: Show the commands for manual execution
    Write-Host "Please run these SQL commands manually in Azure portal:" -ForegroundColor Cyan
    Write-Host $sqlCommand -ForegroundColor White
}